import sqlite3
from settings import sql_creation_settings

DROP_USER_TABLE = '''
    DROP TABLE IF EXISTS USERS
'''

DROP_MOVIE_TABLE = '''
    DROP TABLE IF EXISTS MOVIE
'''

DROP_RESERVATION_TABLE = '''
    DROP TABLE IF EXISTS RESERVATION
'''

DROP_PROJECTION_TABLE = '''
    DROP TABLE IF EXISTS PROJECTION
'''

CREATE_USER_TABLE = '''
    CREATE TABLE IF NOT EXISTS USER (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USERNAME TEXT NOT NULL,
        PASSWORD TEXT NOT NULL
    )
'''

CREATE_MOVIE_TABLE = '''
    CREATE TABLE IF NOT EXISTS MOVIE (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        NAME TEXT NOT NULL,
        RATING REAL NOT NULL
    )
'''

CREATE_PROJECTION_TABLE = '''
    CREATE TABLE IF NOT EXISTS PROJECTION (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        MOVIE_ID INTEGER,
        PR_TYPE TEXT NOT NULL,
        PR_DATE DATETIME NOT NULL,
        PR_TIME TIME NOT NULL,

        FOREIGN KEY(MOVIE_ID) REFERENCES MOVIES(ID)
    )
'''

CREATE_RESERVATION_TABLE = '''
    CREATE TABLE IF NOT EXISTS RESERVATION (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        USER_ID INTEGER,
        PROJECTION_ID INTEGER,
        ROW INTEGER NOT NULL,
        COL INTEGER NOT NULL,

        FOREIGN KEY(USER_ID) REFERENCES USER(ID),
        FOREIGN KEY(PROJECTION_ID) REFERENCES PROJECTION(ID)
    )
'''

INSERT_MOVIE = '''
    INSERT INTO MOVIE(NAME, RATING)
    VALUES(?, ?)
'''

INSERT_USER = '''
    INSERT INTO USER(USERNAME, PASSWORD)
    VALUES(?, ?)
'''

INSERT_PROJECTION = '''
    INSERT INTO PROJECTION(movie_id, PR_TYPE, PR_date, PR_time)
    VALUES(?, ?, ?, ?)
'''

INSERT_RESERVATION = '''
    INSERT INTO RESERVATION(user_id, projection_id, row, col)
    VALUES(?, ?, ?, ?)
'''
